
package com.ipetrushin.syncher.webclient.wsblclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-06-01T15:50:42.360+04:00
 * Generated source version: 2.7.4
 * 
 */
public final class IWSBusinesLogic_WSBusinesLogicPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.wsbl.syncher.ipetrushin.com/", "WSBusinesLogicService");

    private IWSBusinesLogic_WSBusinesLogicPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSBusinesLogicService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSBusinesLogicService ss = new WSBusinesLogicService(wsdlURL, SERVICE_NAME);
        IWSBusinesLogic port = ss.getWSBusinesLogicPort();  
        
        {
        System.out.println("Invoking getListOfJobTitlesByProfession...");
        java.lang.String _getListOfJobTitlesByProfession_arg0 = "";
        java.util.List<java.lang.String> _getListOfJobTitlesByProfession__return = port.getListOfJobTitlesByProfession(_getListOfJobTitlesByProfession_arg0);
        System.out.println("getListOfJobTitlesByProfession.result=" + _getListOfJobTitlesByProfession__return);


        }
        {
        System.out.println("Invoking authorize...");
        java.lang.String _authorize_arg0 = "";
        java.lang.String _authorize_arg1 = "";
        java.lang.String _authorize__return = port.authorize(_authorize_arg0, _authorize_arg1);
        System.out.println("authorize.result=" + _authorize__return);


        }
        {
        System.out.println("Invoking doSynchronization...");
        java.lang.String _doSynchronization_arg0 = "";
        java.lang.String _doSynchronization_arg1 = "";
        java.lang.String _doSynchronization__return = port.doSynchronization(_doSynchronization_arg0, _doSynchronization_arg1);
        System.out.println("doSynchronization.result=" + _doSynchronization__return);


        }
        {
        System.out.println("Invoking getListOfLanguages...");
        java.util.List<java.lang.String> _getListOfLanguages__return = port.getListOfLanguages();
        System.out.println("getListOfLanguages.result=" + _getListOfLanguages__return);


        }
        {
        System.out.println("Invoking getListOfCitiesByCountry...");
        java.lang.String _getListOfCitiesByCountry_arg0 = "";
        java.util.List<java.lang.String> _getListOfCitiesByCountry__return = port.getListOfCitiesByCountry(_getListOfCitiesByCountry_arg0);
        System.out.println("getListOfCitiesByCountry.result=" + _getListOfCitiesByCountry__return);


        }
        {
        System.out.println("Invoking getListOfAvailableWebResources...");
        java.util.List<java.lang.String> _getListOfAvailableWebResources__return = port.getListOfAvailableWebResources();
        System.out.println("getListOfAvailableWebResources.result=" + _getListOfAvailableWebResources__return);


        }
        {
        System.out.println("Invoking getListOfGenders...");
        java.util.List<java.lang.String> _getListOfGenders__return = port.getListOfGenders();
        System.out.println("getListOfGenders.result=" + _getListOfGenders__return);


        }
        {
        System.out.println("Invoking updateResume...");
        java.lang.String _updateResume_arg0 = "";
        java.lang.String _updateResume_arg1 = "";
        java.lang.String _updateResume_arg2 = "";
        java.lang.String _updateResume__return = port.updateResume(_updateResume_arg0, _updateResume_arg1, _updateResume_arg2);
        System.out.println("updateResume.result=" + _updateResume__return);


        }
        {
        System.out.println("Invoking getListOfCountries...");
        java.util.List<java.lang.String> _getListOfCountries__return = port.getListOfCountries();
        System.out.println("getListOfCountries.result=" + _getListOfCountries__return);


        }
        {
        System.out.println("Invoking getRequestResponseStatus...");
        java.lang.String _getRequestResponseStatus_arg0 = "";
        java.lang.String _getRequestResponseStatus__return = port.getRequestResponseStatus(_getRequestResponseStatus_arg0);
        System.out.println("getRequestResponseStatus.result=" + _getRequestResponseStatus__return);


        }
        {
        System.out.println("Invoking getListOfProfessions...");
        java.util.List<java.lang.String> _getListOfProfessions__return = port.getListOfProfessions();
        System.out.println("getListOfProfessions.result=" + _getListOfProfessions__return);


        }
        {
        System.out.println("Invoking registrate...");
        java.util.List<java.lang.String> _registrate_arg0 = null;
        java.lang.String _registrate__return = port.registrate(_registrate_arg0);
        System.out.println("registrate.result=" + _registrate__return);


        }

        System.exit(0);
    }

}
