
package com.ipetrushin.syncher.integration.wsrp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-15T18:28:57.439+04:00
 * Generated source version: 2.7.4
 * 
 */
public final class WSRulesProvider_WSRulesProviderImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.wsrp.syncher.ipetrushin.com/", "WSRulesProviderImplService");

    private WSRulesProvider_WSRulesProviderImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSRulesProviderImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSRulesProviderImplService ss = new WSRulesProviderImplService(wsdlURL, SERVICE_NAME);
        WSRulesProvider port = ss.getWSRulesProviderImplPort();  
        
        {
        System.out.println("Invoking getJobtitleRefMonster...");
        java.lang.String _getJobtitleRefMonster_arg0 = "";
        java.lang.String _getJobtitleRefMonster__return = port.getJobtitleRefMonster(_getJobtitleRefMonster_arg0);
        System.out.println("getJobtitleRefMonster.result=" + _getJobtitleRefMonster__return);


        }
        {
        System.out.println("Invoking getProfessionRefHH...");
        java.lang.String _getProfessionRefHH_arg0 = "";
        java.lang.String _getProfessionRefHH__return = port.getProfessionRefHH(_getProfessionRefHH_arg0);
        System.out.println("getProfessionRefHH.result=" + _getProfessionRefHH__return);


        }
        {
        System.out.println("Invoking getJobtitleRefHH...");
        java.lang.String _getJobtitleRefHH_arg0 = "";
        java.lang.String _getJobtitleRefHH__return = port.getJobtitleRefHH(_getJobtitleRefHH_arg0);
        System.out.println("getJobtitleRefHH.result=" + _getJobtitleRefHH__return);


        }
        {
        System.out.println("Invoking getProfessionRefMonster...");
        java.lang.String _getProfessionRefMonster_arg0 = "";
        java.lang.String _getProfessionRefMonster__return = port.getProfessionRefMonster(_getProfessionRefMonster_arg0);
        System.out.println("getProfessionRefMonster.result=" + _getProfessionRefMonster__return);


        }

        System.exit(0);
    }

}
