package com.ipetrushin.syncher.integration.wsrp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-15T18:28:57.645+04:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "WSRulesProviderImplService", 
                  wsdlLocation = "file:/C:/Users/ipetrush/Documents/GitHub/4course-project/camel-integration-project/src/main/java/com/ipetrushin/syncher/integration/wsrp/ws-rp.wsdl",
                  targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/") 
public class WSRulesProviderImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.wsrp.syncher.ipetrushin.com/", "WSRulesProviderImplService");
    public final static QName WSRulesProviderImplPort = new QName("http://ws.wsrp.syncher.ipetrushin.com/", "WSRulesProviderImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ipetrush/Documents/GitHub/4course-project/camel-integration-project/src/main/java/com/ipetrushin/syncher/integration/wsrp/ws-rp.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSRulesProviderImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ipetrush/Documents/GitHub/4course-project/camel-integration-project/src/main/java/com/ipetrushin/syncher/integration/wsrp/ws-rp.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSRulesProviderImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSRulesProviderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSRulesProviderImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSRulesProviderImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSRulesProviderImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSRulesProviderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSRulesProvider
     */
    @WebEndpoint(name = "WSRulesProviderImplPort")
    public WSRulesProvider getWSRulesProviderImplPort() {
        return super.getPort(WSRulesProviderImplPort, WSRulesProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSRulesProvider
     */
    @WebEndpoint(name = "WSRulesProviderImplPort")
    public WSRulesProvider getWSRulesProviderImplPort(WebServiceFeature... features) {
        return super.getPort(WSRulesProviderImplPort, WSRulesProvider.class, features);
    }

}
