package com.ipetrushin.syncher.integration.wsrp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-15T18:28:57.616+04:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", name = "WSRulesProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface WSRulesProvider {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJobtitleRefMonster", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetJobtitleRefMonster")
    @WebMethod
    @ResponseWrapper(localName = "getJobtitleRefMonsterResponse", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetJobtitleRefMonsterResponse")
    public java.lang.String getJobtitleRefMonster(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProfessionRefHH", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetProfessionRefHH")
    @WebMethod
    @ResponseWrapper(localName = "getProfessionRefHHResponse", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetProfessionRefHHResponse")
    public java.lang.String getProfessionRefHH(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJobtitleRefHH", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetJobtitleRefHH")
    @WebMethod
    @ResponseWrapper(localName = "getJobtitleRefHHResponse", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetJobtitleRefHHResponse")
    public java.lang.String getJobtitleRefHH(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProfessionRefMonster", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetProfessionRefMonster")
    @WebMethod
    @ResponseWrapper(localName = "getProfessionRefMonsterResponse", targetNamespace = "http://ws.wsrp.syncher.ipetrushin.com/", className = "com.ipetrushin.syncher.integration.wsrp.GetProfessionRefMonsterResponse")
    public java.lang.String getProfessionRefMonster(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
