//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.27 at 08:21:30 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/ipetrushin/syncher/request/jaxb/entities", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ipetrushin.syncher.request.jaxb.entities;
