//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 07:14:02 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/ipetrushin/syncher/wsbl/jaxb/entities", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ipetrushin.syncher.wsbl.jaxb.entities;
