--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.864
--   Created On : Friday, 10 May, 2013 
--   DBMS       : DB2 
--   --------------------------------------------------

--  Create Tables 
CREATE TABLE JobTitle ( 
	jobtitle_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	profession INTEGER,
	reference_value_monster INTEGER,
	reference_value_hh INTEGER
)
;

CREATE TABLE JobTitleHH ( 
	jobtitle_id INTEGER NOT NULL,
	name VARCHAR(10) NOT NULL
)
;

CREATE TABLE JobTitleMonster ( 
	jobtitle_id INTEGER NOT NULL,
	name VARCHAR(10) NOT NULL
)
;

CREATE TABLE Profession ( 
	profession_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	reference_value_monster INTEGER,
	reference_value_hh INTEGER
)
;

CREATE TABLE ProfessionHH ( 
	profession_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL
)
;

CREATE TABLE ProfessionMonster ( 
	profession_id INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL
)
;


--  Create Primary Key Constraints 
ALTER TABLE JobTitle ADD CONSTRAINT PK_JobTitle 
	PRIMARY KEY (jobtitle_id)
;


ALTER TABLE JobTitleHH ADD CONSTRAINT PK_JobTitleHH 
	PRIMARY KEY (jobtitle_id)
;


ALTER TABLE JobTitleMonster ADD CONSTRAINT PK_JobTitleMonster 
	PRIMARY KEY (jobtitle_id)
;


ALTER TABLE Profession ADD CONSTRAINT PK_Profession 
	PRIMARY KEY (profession_id)
;


ALTER TABLE ProfessionHH ADD CONSTRAINT PK_ProfessionHH 
	PRIMARY KEY (profession_id)
;


ALTER TABLE ProfessionMonster ADD CONSTRAINT PK_ProfessionMonster 
	PRIMARY KEY (profession_id)
;




--  Create Foreign Key Constraints 
ALTER TABLE JobTitle ADD CONSTRAINT FK_JobTitle_JobTitleHH 
	FOREIGN KEY (reference_value_monster) REFERENCES JobTitleHH (jobtitle_id)
;

ALTER TABLE JobTitle ADD CONSTRAINT FK_JobTitle_JobTitleMonster 
	FOREIGN KEY (reference_value_hh) REFERENCES JobTitleMonster (jobtitle_id)
;

ALTER TABLE JobTitle ADD CONSTRAINT FK_JobTitle_Profession 
	FOREIGN KEY (profession) REFERENCES Profession (profession_id)
;

ALTER TABLE Profession ADD CONSTRAINT FK_Profession_ProfessionHH 
	FOREIGN KEY (reference_value_hh) REFERENCES ProfessionHH (profession_id)
;

ALTER TABLE Profession ADD CONSTRAINT FK_Profession_ProfessionMonster 
	FOREIGN KEY (reference_value_monster) REFERENCES ProfessionMonster (profession_id)
;
